apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: apiconnect
spec:
  ports:
    - port: 443
      targetPort: 443
      nodePort: 30333
      name: https
  selector:
    app: nginx
    tier: proxy
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: apiconnect
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nginx
        tier: proxy
    spec:
      containers:
      - image: registry.ng.bluemix.net/<namespace>/nginx
        name: nginx
        env:
          - name: SOURCE_IP
            value: xxx.xx.xxx.xxx
        ports:
        - containerPort: 443
          name: https
